# demo-app-dev.yml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db
    username: dev_user
    password: dev_password
  application:
    name: demo-app

server:
  port: 8081

app:
  message: Welcome to the Development Environment
  feature-flag: true
